#!/usr/bin/env python3
import argparse
import pathlib
import xml.etree.ElementTree as ET


def parse_args():
    parser = argparse.ArgumentParser(description="Generate course tilemap asset declarations from a split TMX.")
    parser.add_argument("--tmx", required=True, help="Source TMX path.")
    parser.add_argument("--course-width-tiles", required=True, type=int, help="Course width in tiles.")
    parser.add_argument("--course-height-tiles", required=True, type=int, help="Course height in tiles.")
    parser.add_argument("--header", required=True, help="Generated header path.")
    parser.add_argument("--source", required=True, help="Generated include path.")
    return parser.parse_args()


def count_courses(tmx_path, course_w, course_h):
    root = ET.parse(tmx_path).getroot()
    map_w = int(root.attrib["width"])
    map_h = int(root.attrib["height"])

    if map_w % course_w != 0 or map_h % course_h != 0:
        raise ValueError(
            f"TMX map {map_w}x{map_h} is not divisible by course size {course_w}x{course_h}."
        )

    return (map_w // course_w) * (map_h // course_h)


def write_header(path, count, asset_stem):
    lines = [
        "/* Auto-generated by tools/gen_course_assets.py. Do not edit manually. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]

    for i in range(count):
        lines.append(f"extern uint8_t _course_map{i}_start;")
        lines.append(f"extern uint8_t _course_map{i}_end;")

    lines.extend([
        "",
        "extern uint8_t* course_maps[];",
        "extern uint8_t course_map_count;",
        "",
        "#define COURSE_MAPS_ASM \\",
    ])

    for i in range(count):
        suffix = "" if i == count - 1 else " \\"
        lines.append(f"    \"__course_map{i}_start:\\n\" \\")
        lines.append(f"    \"    .incbin \\\"assets/{asset_stem}{i:04d}.ztm\\\"\\n\" \\")
        lines.append(f"    \"__course_map{i}_end:\\n\"{suffix}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def write_source(path, count):
    lines = [
        "/* Auto-generated by tools/gen_course_assets.py. Do not edit manually. */",
        '#include "course_assets.generated.h"',
        "",
        "uint8_t* course_maps[] = {",
    ]

    for i in range(count):
        lines.append(f"    &_course_map{i}_start,")

    lines.extend([
        "};",
        "uint8_t course_map_count = sizeof(course_maps) / sizeof(course_maps[0]);",
    ])

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def main():
    args = parse_args()
    asset_stem = pathlib.Path(args.tmx).stem
    count = count_courses(
        pathlib.Path(args.tmx),
        args.course_width_tiles,
        args.course_height_tiles,
    )
    write_header(pathlib.Path(args.header), count, asset_stem)
    write_source(pathlib.Path(args.source), count)


if __name__ == "__main__":
    main()
