#ifndef ZGOLF_CONFIG_H
#define ZGOLF_CONFIG_H

#define SCREEN_MODE   ZVB_CTRL_VID_MODE_GFX_640_8BIT
#define SCREEN_WIDTH  640
#define SCREEN_HEIGHT 480

#define TILE_PIXEL_SIZE 16
#define TILE_PIXEL_SHIFT 4
#define TILE_PIXEL_MASK (TILE_PIXEL_SIZE - 1)
#define SCREEN_TILES_W 40
#define SCREEN_TILES_H 30

#define COURSE_TILES_W 40
#define COURSE_TILES_H 30
#define GAME_COURSE_COUNT 15
#define HUD_START_ROW 24
#define PLAYFIELD_TILES_H HUD_START_ROW
#define PLAYFIELD_HEIGHT (PLAYFIELD_TILES_H * TILE_PIXEL_SIZE)

#define COURSE_LAYER 0
#define UI_LAYER     1

#define EMPTY_TILE   255
#define TILEMAP_GID_OFFSET 0

#define TILE_ID_WALL   0
#define TILE_ID_FLOOR  1
#define TILE_ID_BALL   2
#define TILE_ID_MARKER 3
#define TILE_ID_HOLE   4
#define TILE_ID_POWER  5
#define TILE_ID_POWER_MARKER 63
#define TILE_ID_WATER_FIRST 43
#define TILE_ID_WATER_LAST  51
#define TILE_ID_DEFLECT_SLASH_1     52
#define TILE_ID_DEFLECT_BACKSLASH_1 53
#define TILE_ID_DEFLECT_SLASH_2     54
#define TILE_ID_DEFLECT_BACKSLASH_2 55
#define FONT_DIGIT_TILE 6
#define FONT_ALPHA_A_TILE 16

#define SPRITE_ARENA_SIZE 8
#define AIM_MARKER_COUNT 6
#define AIM_MARKER_SPACING_PIXELS 12
#define AIM_DIRECTION_COUNT 32
#define AIM_VECTOR_SHIFT 7
#define AIM_INPUT_REPEAT_FRAMES 8
#define AIM_INPUT_MAX_HELD_STEPS 32

#define BALL_START_TILE_X 4
#define BALL_START_TILE_Y 20
#define COURSE_DEFAULT_HOLE_TILE_X 34
#define COURSE_DEFAULT_HOLE_TILE_Y 4
#define COURSE_DEFAULT_PAR 3

#define FIXED_SHIFT 4
#define FIXED_ONE   16

#define SHOT_VELOCITY_SHIFT 5
#define POWER_BAR_STEP_FRAMES 16
#define SHOT_POWER_STEP_1  8
#define SHOT_POWER_STEP_2  11
#define SHOT_POWER_STEP_3  16
#define SHOT_POWER_STEP_4  19
#define SHOT_POWER_STEP_5  23
#define SHOT_POWER_STEP_6  29
#define SHOT_POWER_STEP_7  35
#define SHOT_POWER_STEP_8  43
#define SHOT_POWER_STEPS { \
    SHOT_POWER_STEP_1, \
    SHOT_POWER_STEP_2, \
    SHOT_POWER_STEP_3, \
    SHOT_POWER_STEP_4, \
    SHOT_POWER_STEP_5, \
    SHOT_POWER_STEP_6, \
    SHOT_POWER_STEP_7, \
    SHOT_POWER_STEP_8  \
}

#define POWER_BAR_X 16
#define POWER_BAR_Y 26
#define POWER_BAR_MARKER_Y 27
#define POWER_BAR_SEGMENTS 8

#define HUD_COURSE_LABEL_X 2
#define HUD_COURSE_LABEL_Y 25
#define HUD_COURSE_VALUE_X 9
#define HUD_PAR_LABEL_X 2
#define HUD_PAR_LABEL_Y 26
#define HUD_PAR_VALUE_X 9
#define HUD_STROKE_LABEL_X 2
#define HUD_STROKE_LABEL_Y 27
#define HUD_STROKE_VALUE_X 9
#define HUD_SCORE_LABEL_X 2
#define HUD_SCORE_LABEL_Y 28
#define HUD_SCORE_VALUE_X 9
#define HUD_POWER_LABEL_X 18
#define HUD_POWER_LABEL_Y 25
#define HUD_NUMBER_WIDTH 2
#define HUD_WATER_LINE_1_X 32
#define HUD_WATER_LINE_1_Y 27
#define HUD_WATER_LINE_1_WIDTH 7
#define HUD_WATER_LINE_2_X 30
#define HUD_WATER_LINE_2_Y 28
#define HUD_WATER_LINE_2_WIDTH 9

#define BALL_FRICTION 31
#define BALL_FRICTION_SHIFT 5
#define BALL_FRICTION_ROUNDING (1 << (BALL_FRICTION_SHIFT - 1))
#define BALL_STOP_SPEED 1
#define BALL_DIAGONAL_STOP_SPEED 4
#define BALL_BOUNCE_FACTOR 12
#define BALL_COLLISION_RADIUS_PIXELS 3
#define BALL_HOLE_MAX_SPEED 24
#define BALL_HOLE_PROBE_PIXELS 5
#define BALL_MAX_STEP_FIXED 128
#define DEFLECTOR_SOLID_HALF_WIDTH_PIXELS 3

#define BALL_MIN_FIXED 0
#define BALL_MAX_X_FIXED ((SCREEN_WIDTH + TILE_PIXEL_SIZE) << FIXED_SHIFT)
#define BALL_MAX_Y_FIXED ((PLAYFIELD_HEIGHT + TILE_PIXEL_SIZE) << FIXED_SHIFT)

#define SHOOT_BUTTON_MASK BUTTON_B
#define EXIT_BUTTON_MASK  BUTTON_SELECT

#define TILESET_LOAD_CHUNK_BYTES 1024
#define TILESET_4BIT_VRAM_SCALE  2

#endif
